### ISSUE TITLE
":eval yes" source code block header argument

### ISSUE THREAD

**Issue by ckhroulev** [fniessen/refcard-org-babel#1]
According to [the Org Mode Manual](http://orgmode.org/manual/eval.html#eval), `:eval yes` is not recognized by `org-mode`. (I also failed to find any uses of `:eval yes` reading Org sources, both the 8.2.10 release and the `master` branch.)

Could you please point me to the code using the `yes` value of the `:eval` header argument or update the ref. card?

Thanks!

PS: This is motivated by [a question on Emacs.SE](http://emacs.stackexchange.com/q/2945/2355).

**Comment by fniessen** [comment]
On the principle, you're indeed right (I wasn't aware of that -- thanks for pinging me about the issue, and pointing me to the above thread).

Though, ":eval yes" does well override any ":eval no" that would be set a the file or subtree level. It does work that way...

Otherwise, what's the solution for re-enabling the evaluation?

See my MWE on Emacs.SE for testing purpose.

**Comment by ckhroulev** [comment]
Thanks for responding!

I agree that `:eval foo` undoes the effect of `:eval no` (and other values disabling evaluation) set at the sub-tree level, but try exporting this:

```
#+BEGIN_SRC python :exports results
return "evaluated after prompting the user"
#+END_SRC

#+BEGIN_SRC python :exports results :eval yes
return "also evaluated after prompting the user"
#+END_SRC
```

The text of your ref. card can be interpreted as "with `:eval yes` a source code block is always evaluated without prompting the user, so Org should not ask me about evaluating the second source code block regardless of the value of `org-confirm-babel-evaluate`", and this is not supported by Org (even though it _is_ a useful feature).

**Comment by fniessen** [comment]
THANKS for your note!

I've updated the documentation taking care of your remark:

```
:eval <any-value-other-than-the-reserved-ones> ::
 If the ~org-confirm-babel-evaluate~ variable is non-nil, allows evaluation of
 the code block (both interactively and during export) without
 a confirmation from the user.  It undoes the effect of ~:eval no~ (and other
 values disabling evaluation) set at the file or sub-tree level. \\
 (default)
```

Please react if you still find it uncomplete or not fully correct. But I think it now is!
