### ISSUE TITLE
Web rendering problems and/or recommend viewing in emacs

### ISSUE THREAD

**Issue by steady137** [fniessen/refcard-org-babel#10]
I'm new to org and babel and appreciate all the work that's gone into explanations like this refcard making it accessible. I've noticed some web pages with examples that don't render correctly from worg, readthedocs, and github which has caused me confusion. I only recently realized that viewing the .org files in emacs will let me see the example org-babel blocks that are missing in the web renderings.

If the rendering is known to be missing example blocks, a note in the Readme.org to recommend viewing in emacs could be helpful: "Note: rendering for web hides the example org-babel blocks. Please use Emacs to view the .org files to show all content."

Many thanks for your contribution.

**Comment by fniessen** [comment]
@steady137 Thanks for the hint!

**Comment by E3D3** [comment]
The message is not visible in the README on github. And also not the lines beginning with  the `#` character.

**Comment by fniessen** [comment]
@steady137  Thanks for letting me know!
