### ISSUE TITLE
So what is in the file "~/src/org-style/setup/bigblow-pirilampo.setup"?

### ISSUE THREAD

**Issue by Richard-Cranium** [fniessen/refcard-org-babel#2]
It's difficult to test any changes against the exported HTML without the contents of this file.  You should probably check that in to github too and change the reference accordingly.

**Comment by fniessen** [comment]
I agree that I should have added it in the first place. Here it is. DONE!

**Comment by Richard-Cranium** [comment]
Thanks!  It's a good reference and I would like to test any pull requests before I send them.  :)

On February 2, 2015 9:55:08 AM CST, Fabrice Niessen notifications@github.com wrote:

> I agree that I should have added it in the first place. Here it is.
> DONE!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fniessen/refcard-org-babel/issues/2#issuecomment-72480654

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
