### ISSUE TITLE
Help, How to preserve leading zeros of table cells when using header variable

### ISSUE THREAD

**Issue by yssource** [fniessen/refcard-org-babel#3]
- [demo](#org0068a01)

There are ****string-type numbers**** in 'id' column originally, but it is always interpreted as **numbers** by org-babel.
I wonder how to keep those leading zeros in org-babel?
Thanks.

<a id="org0068a01"></a>

# demo

| id   | name   | age |
|---- |------ |--- |
| 0001 | Apollo | 16  |
| 0002 | Bmw    | 16  |

```org
#+name: TBL
|   id | name   | age |
|------|--------|-----|
| 0001 | Apollo |  16 |
| 0002 | Bmw    |  16 |

#+BEGIN_SRC python :results output :var tbl=TBL
  print(tbl)
#+END_SRC
#+RESULTS:
: [[1, 'Apollo', 16], [2, 'Bmw', 16]]
```

**Comment by fniessen** [comment]
@yssource This is in fact a question to be addressed to the Org mode mailing list. Thanks.

**Comment by yssource** [comment]
Thanks. 
I find a way to solve my problem. 
Though It's not the proper place opening the issue here, maybe It will help others who have the same problem.

```org
#+BEGIN_SRC emacs-lisp
  (defun my/org-babel--string-to-number (string)
    "If STRING represents a number return its value.
  Otherwise return nil."
    (and (string-match-p "\\`-?\\([1-9]\\|[0-9]*\\.\\)[0-9]*\\'" string)
         (string-to-number string)))

  (advice-add 'org-babel--string-to-number :override 'my/org-babel--string-to-number)

  ;; test
  (mapcar (lambda (string)
            (and (my/org-babel--string-to-number string)
                 t))
          '("001" "0.1" "00.1" "100" "100.1"))
  ;; => (nil t t t t)
#+END_SRC

#+RESULTS:
| nil | t | t | t | t |
```

**Comment by ZelphirKaltstahl** [comment]
@yssource Thanks for sharing that, in case anyone else needs it and finds it here.
