### ISSUE TITLE
How did you generate the readthedocs markdown from the org-babel document?

### ISSUE THREAD

**Issue by vonHabsi** [fniessen/refcard-org-babel#4]
How did you generate the readthedocs markdown from the org-babel document?

I want to generate the emacs documentation in that format as I find it easier to read and would like to know what tools and scripts you use?

I assume that most of it was generated directly from the official org-babel documentation.

**Comment by fniessen** [comment]
Hi vonHabsi, not sure to understand… You want to read doc in file.md format, or in file.html format (using the RTO CSS I've made public)?

In any case, for exporting an Org file to Markdown, use the exporter `C-c C-e m o`.

Does this answer your question?

**Comment by vonHabsi** [comment]
I want to know if the markdown files were generated from the official org refcard or you created the documents yourself and exported them to the readthedocs markdown format.

In short I'd like to know the original document format Org Refcard is created in and where it can be found.
