### ISSUE TITLE
Org babel `:var` multiple arguments does not accept `,` as a separator in emacs 28.1, org 9.6.1

### ISSUE THREAD

**Issue by jmeissen** [fniessen/refcard-org-babel#8]
First of all, fantastic reference! I've been a happy user for a while now. I recently discovered an error though.

When using a comma after a string literal, `org-babel-ref-resolve` says it cannot find the reference in the buffer.

I'll send a PR when I got the time.

**Comment by fniessen** [comment]
Great @jmeissen that you find it useful for you too...
Thanks for providing a PR, indeed!
